CREATE DATABASE [QuanLyThuVien]
GO
USE [QuanLyThuVien]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ACCOUNT](
	[IDAccount] [varchar](50) NOT NULL,
	[PasswordAccount] [nvarchar](256) NOT NULL,
	[TypeOfAccount] [varchar](50) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[IDAccount] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ADMIN]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ADMIN](
	[IDAdmin] [varchar](50) NOT NULL,
	[IDAccount] [varchar](50) NOT NULL,
	[HoTen] [nvarchar](100) NOT NULL,
	[NgaySinh] [date] NOT NULL,
	[DiaChi] [nvarchar](200) NULL,
	[Email] [varchar](100) NOT NULL,
	[SDT] [varchar](20) NOT NULL,
 CONSTRAINT [PK_ADMIN] PRIMARY KEY CLUSTERED 
(
	[IDAdmin] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BCTKMUONSACH]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BCTKMUONSACH](
	[MaBCTKMuonSach] [varchar](50) NOT NULL,
	[Thang] [date] NOT NULL,
	[TongSoLuotMuon] [int] NOT NULL,
 CONSTRAINT [PK_BCTKMuonSach] PRIMARY KEY CLUSTERED 
(
	[MaBCTKMuonSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BCTKTRATRE]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BCTKTRATRE](
	[MaBCTKTraTre] [varchar](50) NOT NULL,
	[Ngay] [date] NOT NULL,
 CONSTRAINT [PK_BCTKTraTre] PRIMARY KEY CLUSTERED 
(
	[MaBCTKTraTre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CHITIETPHANQUYEN]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CHITIETPHANQUYEN](
	[IDAccount] [varchar](50) NOT NULL,
	[IDPer] [varchar](50) NOT NULL,
	[suspended] [bit] NOT NULL,
 CONSTRAINT [PK_CHITIETPHANQUYEN] PRIMARY KEY CLUSTERED 
(
	[IDPer] ASC,
	[IDAccount] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CTBCTKMUONSACH]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CTBCTKMUONSACH](
	[MaBCTKMuonSach] [varchar](50) NOT NULL,
	[MaTheLoai] [varchar](50) NOT NULL,
	[SoLuotMuon] [int] NOT NULL,
	[TiLe] [float] NOT NULL,
 CONSTRAINT [PK_CTBCTKMuonSach] PRIMARY KEY CLUSTERED 
(
	[MaBCTKMuonSach] ASC,
	[MaTheLoai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CTBCTKTRATRE]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CTBCTKTRATRE](
	[MaBCTKTraTre] [varchar](50) NOT NULL,
	[MaPhieuMS] [varchar](50) NOT NULL,
	[MaSach] [varchar](50) NOT NULL,
	[SoNgayTraTre] [int] NOT NULL,
 CONSTRAINT [PK_CTBCTKTRATRE] PRIMARY KEY CLUSTERED 
(
	[MaBCTKTraTre] ASC,
	[MaPhieuMS] ASC,
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CTPHIEUMUON]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CTPHIEUMUON](
	[MaPhieuMS] [varchar](50) NOT NULL,
	[MaSach] [varchar](50) NOT NULL,
	[HanTra] [datetime] NOT NULL,
	[TinhTrangMuon] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_CTPHIEUMUON] PRIMARY KEY CLUSTERED 
(
	[MaPhieuMS] ASC,
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DOCGIA]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DOCGIA](
	[MaDocGia] [varchar](50) NOT NULL,
	[HoTen] [nvarchar](200) NOT NULL,
	[NgaySinh] [date] NOT NULL,
	[DiaChi] [nvarchar](200) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[NgayLapThe] [date] NOT NULL,
	[NgayHetHan] [date] NOT NULL,
	[MaLoaiDocGia] [varchar](50) NOT NULL,
	[IDAccount] [varchar](50) NOT NULL,
	[SDT] [varchar](20) NOT NULL,
 CONSTRAINT [PK_DOCGIA] PRIMARY KEY CLUSTERED 
(
	[MaDocGia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOAIDOCGIA]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOAIDOCGIA](
	[MaLoaiDocGia] [varchar](50) NOT NULL,
	[TenLoaiDocGia] [nvarchar](100) NOT NULL,
	[SoSachToiDa] [int] NOT NULL,
	[ThoiHanMuon] [int] NOT NULL,
 CONSTRAINT [PK_LOAIDOCGIA] PRIMARY KEY CLUSTERED 
(
	[MaLoaiDocGia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PERMISSION]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PERMISSION](
	[IDPer] [varchar](50) NOT NULL,
	[NamePer] [nvarchar](100) NOT NULL,
	[CodeAction] [varchar](100) NOT NULL,
	[Description] [nvarchar](200) NULL,
 CONSTRAINT [PK_PERMISSION] PRIMARY KEY CLUSTERED 
(
	[IDPer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PHIEUMUONSACH]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PHIEUMUONSACH](
	[MaPhieuMS] [varchar](50) NOT NULL,
	[MaDocGia] [varchar](50) NOT NULL,
	[NgayMuon] [date] NOT NULL,
 CONSTRAINT [PK_PHIEUMUONSACH] PRIMARY KEY CLUSTERED 
(
	[MaPhieuMS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[YEUCAUMUON]
(
MaYeuCau INT identity (1,1), 
MaDocGia varchar (50) not null,
MaSach varchar (50) not null,
NgayYeuCau DATETIME Default GETDATE (), 
TrangThai NVARCHAR (20) DEFAULT N'Chờ duyệt'
CONSTRAINT [PK_YEUCAUMUON] PRIMARY KEY CLUSTERED 
(
	[MaYeuCau] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[YEUCAUMUON]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PHIEUTHUTIENPHAT](
	[MaPhieuThuTP] [varchar](50) NOT NULL,
	[MaDocGia] [varchar](50) NOT NULL,
	[TongNo] [decimal](18, 2) NOT NULL,
	[SoTienThu] [decimal](18, 2) NOT NULL,
	[ConLai] [decimal](18, 2) NOT NULL,
	[NgayThu] [datetime] NOT NULL,
 CONSTRAINT [PK_PHIEUTHUTIENPHAT] PRIMARY KEY CLUSTERED 
(
	[MaPhieuThuTP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PHIEUTRASACH]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PHIEUTRASACH](
	[MaPhieuMS] [varchar](50) NOT NULL,
	[MaSach] [varchar](50) NOT NULL,
	[NgayTra] [date] NOT NULL,
	[SoNgayMuon] [int] NOT NULL,
	[TienPhat] [decimal](18, 2) NOT NULL,
	[TinhTrangTraSach] [nvarchar](200) NOT NULL,
	[GhiChu] [nvarchar](200) NULL,
 CONSTRAINT [PK_PHIEUTRASACH] PRIMARY KEY CLUSTERED 
(
	[MaPhieuMS] ASC,
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SACH]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DAUSACH](
	[MaDauSach] int identity(1,1)  NOT NULL,
	[TenDauSach] [nvarchar](100) NOT NULL,
	[MaTheLoai] [varchar](50) NOT NULL,
	[NamXuatBan] [int] NOT NULL,
	[NhaXuatBan] [nvarchar](100) NULL,
 CONSTRAINT [PK_DAUSACH] PRIMARY KEY CLUSTERED 
(
	[MaDauSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TACGIA]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DAUSACH_TACGIA](
	[MaDauSach] int not null,
	[MaTacGia] int  not null,
 CONSTRAINT [PK_DAUSACH_TACGIA] PRIMARY KEY CLUSTERED 
(
	[MaDauSach] ASC,
	[MaTacGia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TACGIA]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SACH](
	[MaSach] [varchar] (50) not null,
	[MaDauSach] int not null,
	[NgayNhap] [date] NOT NULL,
	[TriGia] [decimal](18, 0) NOT NULL,
	[MaTinhTrang] [varchar](50) NOT NULL,
 CONSTRAINT [PK_SACH] PRIMARY KEY CLUSTERED 
(
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TACGIA]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TACGIA](
    [MaTacGia] INT IDENTITY(1,1) NOT NULL,
    [TenTacGia] NVARCHAR(100) NOT NULL,
    [NamSinh] INT NOT NULL,
 CONSTRAINT [PK_TACGIA] PRIMARY KEY CLUSTERED 
(
    [MaTacGia] ASC
)WITH (
    PAD_INDEX = OFF, 
    STATISTICS_NORECOMPUTE = OFF, 
    IGNORE_DUP_KEY = OFF, 
    ALLOW_ROW_LOCKS = ON, 
    ALLOW_PAGE_LOCKS = ON
) ON [PRIMARY]
) ON [PRIMARY];

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[THAMSO]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THAMSO](
	[MaThamSo] [int] IDENTITY(1,1) NOT NULL,
	[TuoiToiDa] [int] NOT NULL,
	[TuoiToiThieu] [int] NOT NULL,
	[ThoiHanThe] [int] NOT NULL,
	[KhoangCachXB] [int] NOT NULL,
	[SoNgayMuonMax] [int] NOT NULL,
	[SoSachMuonMax] [int] NOT NULL,
	[TPTraTreMotNgay] [decimal](18, 0) NOT NULL,
	[SoLuongTheLoaiMax] [int] NOT NULL,
	[SoLuongTacGia] [int] NOT NULL,
 CONSTRAINT [PK_THAMSO] PRIMARY KEY CLUSTERED 
(
	[MaThamSo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[THELOAI]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[THELOAI](
	[MaTheLoai] [varchar](50) NOT NULL,
	[TenTheLoai] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_THELOAI] PRIMARY KEY CLUSTERED 
(
	[MaTheLoai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TINHTRANG]    Script Date: 6/28/2019 11:52:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TINHTRANG](
	[MaTinhTrang] [varchar](50) NOT NULL,
	[TenTinhTrang] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_TINHTRANG] PRIMARY KEY CLUSTERED 
(
	[MaTinhTrang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[THAMSO] ON 
SET IDENTITY_INSERT [dbo].[THAMSO] OFF
SET ANSI_PADDING ON

GO
/****** Object:  Index [UQ_ADMIN_IDAccount]    Script Date: 6/28/2019 11:52:33 PM ******/
ALTER TABLE [dbo].[ADMIN] ADD  CONSTRAINT [UQ_ADMIN_IDAccount] UNIQUE NONCLUSTERED 
(
	[IDAccount] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UQ_DOCGIA_Email]    Script Date: 6/28/2019 11:52:33 PM ******/
ALTER TABLE [dbo].[DOCGIA] ADD  CONSTRAINT [UQ_DOCGIA_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UQ_DOCGIA_IDUser]    Script Date: 6/28/2019 11:52:33 PM ******/
ALTER TABLE [dbo].[DOCGIA] ADD  CONSTRAINT [UQ_DOCGIA_IDAccount] UNIQUE NONCLUSTERED 
(
	[IDAccount] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTBCTKTRATRE] ADD  CONSTRAINT [DF_CTBCTKTRATRE_SoNgayTraTre]  DEFAULT ((0)) FOR [SoNgayTraTre]
GO
ALTER TABLE [dbo].[PHIEUTRASACH] ADD  CONSTRAINT [DF_PHIEUTRASACH_TienPhat]  DEFAULT ((0)) FOR [TienPhat]
GO
ALTER TABLE [dbo].[ADMIN]  WITH CHECK ADD  CONSTRAINT [FK_ADMIN_ACCOUNT] FOREIGN KEY([IDAccount])
REFERENCES [dbo].[ACCOUNT] ([IDAccount])
GO
ALTER TABLE [dbo].[ADMIN] CHECK CONSTRAINT [FK_ADMIN_ACCOUNT]
GO
ALTER TABLE [dbo].[CHITIETPHANQUYEN]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHANQUYEN_ACCOUNT] FOREIGN KEY([IDAccount])
REFERENCES [dbo].[ACCOUNT] ([IDAccount])
GO
ALTER TABLE [dbo].[CHITIETPHANQUYEN] CHECK CONSTRAINT [FK_CHITIETPHANQUYEN_ACCOUNT]
GO
ALTER TABLE [dbo].[CHITIETPHANQUYEN]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHANQUYEN_PERMISSION] FOREIGN KEY([IDPer])
REFERENCES [dbo].[PERMISSION] ([IDPer])
GO
ALTER TABLE [dbo].[CHITIETPHANQUYEN] CHECK CONSTRAINT [FK_CHITIETPHANQUYEN_PERMISSION]
GO
ALTER TABLE [dbo].[CTBCTKMUONSACH]  WITH CHECK ADD  CONSTRAINT [FK_CTBCTKMUONSACH_BCTKMUONSACH] FOREIGN KEY([MaBCTKMuonSach])
REFERENCES [dbo].[BCTKMUONSACH] ([MaBCTKMuonSach])
GO
ALTER TABLE [dbo].[CTBCTKMUONSACH] CHECK CONSTRAINT [FK_CTBCTKMUONSACH_BCTKMUONSACH]
GO
ALTER TABLE [dbo].[CTBCTKMUONSACH]  WITH CHECK ADD  CONSTRAINT [FK_CTBCTKMUONSACH_THELOAI] FOREIGN KEY([MaTheLoai])
REFERENCES [dbo].[THELOAI] ([MaTheLoai])
GO
ALTER TABLE [dbo].[CTBCTKMUONSACH] CHECK CONSTRAINT [FK_CTBCTKMUONSACH_THELOAI]
GO
ALTER TABLE [dbo].[CTBCTKTRATRE]  WITH CHECK ADD  CONSTRAINT [FK_CTBCTKTRATRE_BCTKTRATRE] FOREIGN KEY([MaBCTKTraTre])
REFERENCES [dbo].[BCTKTRATRE] ([MaBCTKTraTre])
GO
ALTER TABLE [dbo].[CTBCTKTRATRE] CHECK CONSTRAINT [FK_CTBCTKTRATRE_BCTKTRATRE]
GO
ALTER TABLE [dbo].[CTBCTKTRATRE]  WITH CHECK ADD  CONSTRAINT [FK_CTBCTKTRATRE_PHIEUTRASACH] FOREIGN KEY([MaPhieuMS], [MaSach])
REFERENCES [dbo].[PHIEUTRASACH] ([MaPhieuMS], [MaSach])
GO
ALTER TABLE [dbo].[CTBCTKTRATRE] CHECK CONSTRAINT [FK_CTBCTKTRATRE_PHIEUTRASACH]
GO
ALTER TABLE [dbo].[CTPHIEUMUON]  WITH CHECK ADD  CONSTRAINT [FK_CTPHIEUMUON_PHIEUMUONSACH] FOREIGN KEY([MaPhieuMS])
REFERENCES [dbo].[PHIEUMUONSACH] ([MaPhieuMS])
GO
ALTER TABLE [dbo].[CTPHIEUMUON] CHECK CONSTRAINT [FK_CTPHIEUMUON_PHIEUMUONSACH]
GO
ALTER TABLE [dbo].[CTPHIEUMUON]  WITH CHECK ADD  CONSTRAINT [FK_CTPHIEUMUON_SACH] FOREIGN KEY([MaSach])
REFERENCES [dbo].[SACH] ([MaSach])
GO
ALTER TABLE [dbo].[CTPHIEUMUON] CHECK CONSTRAINT [FK_CTPHIEUMUON_SACH]
GO
ALTER TABLE [dbo].[DOCGIA]  WITH CHECK ADD  CONSTRAINT [FK_DOCGIA_LOAIDOCGIA] FOREIGN KEY([MaLoaiDocGia])
REFERENCES [dbo].[LOAIDOCGIA] ([MaLoaiDocGia])
GO
ALTER TABLE [dbo].[DOCGIA] CHECK CONSTRAINT [FK_DOCGIA_LOAIDOCGIA]
GO
ALTER TABLE [dbo].[DOCGIA]  WITH CHECK ADD  CONSTRAINT [FK_DOCGIA_ACCOUNT] FOREIGN KEY([IDAccount])
REFERENCES [dbo].[ACCOUNT] ([IDAccount])
GO
ALTER TABLE [dbo].[DOCGIA] CHECK CONSTRAINT [FK_DOCGIA_ACCOUNT]
GO
ALTER TABLE [dbo].[PHIEUMUONSACH]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUMUONSACH_DOCGIA] FOREIGN KEY([MaDocGia])
REFERENCES [dbo].[DOCGIA] ([MaDocGia])
GO
ALTER TABLE [dbo].[PHIEUMUONSACH] CHECK CONSTRAINT [FK_PHIEUMUONSACH_DOCGIA]
GO
ALTER TABLE [dbo].[PHIEUTHUTIENPHAT]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUTHUTIENPHAT_DOCGIA] FOREIGN KEY([MaDocGia])
REFERENCES [dbo].[DOCGIA] ([MaDocGia])
GO
ALTER TABLE [dbo].[PHIEUTHUTIENPHAT] CHECK CONSTRAINT [FK_PHIEUTHUTIENPHAT_DOCGIA]
GO
ALTER TABLE [dbo].[PHIEUTRASACH]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUTRASACH_CTPHIEUMUON] FOREIGN KEY([MaPhieuMS], [MaSach])
REFERENCES [dbo].[CTPHIEUMUON] ([MaPhieuMS], [MaSach])
GO
ALTER TABLE [dbo].[PHIEUTRASACH] CHECK CONSTRAINT [FK_PHIEUTRASACH_CTPHIEUMUON]
GO
ALTER TABLE [dbo].[DAUSACH_TACGIA]  WITH CHECK ADD  CONSTRAINT [FK_DAUSACH_TACGIA_DAUSACH] FOREIGN KEY([MaDauSach])
REFERENCES [dbo].[DAUSACH] ([MaDauSach])
GO
ALTER TABLE [dbo].[DAUSACH_TACGIA] CHECK CONSTRAINT [FK_DAUSACH_TACGIA_DAUSACH]
GO
ALTER TABLE [dbo].[DAUSACH_TACGIA]  WITH CHECK ADD  CONSTRAINT [FK_DAUSACH_TACGIA_TACGIA] FOREIGN KEY([MaTacGia])
REFERENCES [dbo].[TACGIA] ([MaTacGia])
GO
ALTER TABLE [dbo].[DAUSACH_TACGIA] CHECK CONSTRAINT [FK_DAUSACH_TACGIA_TACGIA]
GO
ALTER TABLE [dbo].[DAUSACH]  WITH CHECK ADD  CONSTRAINT [FK_DAUSACH_THELOAI] FOREIGN KEY([MaTheLoai])
REFERENCES [dbo].[THELOAI] ([MaTheLoai])
GO
ALTER TABLE [dbo].[DAUSACH] CHECK CONSTRAINT [FK_DAUSACH_THELOAI]
GO
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_TINHTRANG] FOREIGN KEY([MaTinhTrang])
REFERENCES [dbo].[TINHTRANG] ([MaTinhTrang])
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_TINHTRANG]
GO
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_DAUSACH] FOREIGN KEY([MaDauSach])
REFERENCES [dbo].[DAUSACH] ([MaDauSach])
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_DAUSACH]
GO

ALTER TABLE [dbo].[YEUCAUMUON]  WITH CHECK ADD  CONSTRAINT [FK_YEUCAUMUON_DOCGIA] FOREIGN KEY([MaDocGia])
REFERENCES [dbo].[DOCGIA] ([MaDocGia])
GO
ALTER TABLE [dbo].[YEUCAUMUON] CHECK CONSTRAINT [FK_YEUCAUMUON_DOCGIA]
GO

ALTER TABLE [dbo].[YEUCAUMUON]  WITH CHECK ADD  CONSTRAINT [FK_YEUCAUMUON_SACH] FOREIGN KEY([MaSach])
REFERENCES [dbo].[SACH] ([MaSach])
GO
ALTER TABLE [dbo].[YEUCAUMUON] CHECK CONSTRAINT [FK_YEUCAUMUON_SACH]
GO
INSERT [dbo].[THAMSO] VALUES (55, 18, 6, 8, 4, 5, CAST(1000 AS Decimal(18, 0)), 50, 100)
--Insert account
INSERT [dbo].[ACCOUNT] ([IDAccount], [PasswordAccount], [TypeOfAccount]) VALUES ('100000', '12345678', N'USER')
INSERT [dbo].[ACCOUNT] ([IDAccount], [PasswordAccount], [TypeOfAccount]) VALUES ('100001', '12345678', N'USER')
INSERT [dbo].[ACCOUNT] ([IDAccount], [PasswordAccount], [TypeOfAccount]) VALUES ('100002', '12345678', N'USER')
INSERT [dbo].[ACCOUNT] ([IDAccount], [PasswordAccount], [TypeOfAccount]) VALUES ('100003', '12345678', N'USER')
INSERT [dbo].[ACCOUNT] ([IDAccount], [PasswordAccount], [TypeOfAccount]) VALUES ('admin', 'admin@123', N'ADMIN')
--Insert admin
INSERT [dbo].[ADMIN] ([IDAdmin], [IDAccount], [HoTen], [NgaySinh], [DiaChi], [Email], [SDT]) VALUES (N'AD0001', N'admin', N'Nguyễn Văn A', CAST(0x000072B900000000 AS DateTime), N'TP.HCM', N'admin@gmail.com', N'0327559839')
--insert loại độc giả
INSERT [dbo].[LOAIDOCGIA] ([MaLoaiDocGia], [TenLoaiDocGia], [SoSachToiDa], [ThoiHanMuon]) VALUES (N'LDG1', N'Sinh Viên', 3, 5)
INSERT [dbo].[LOAIDOCGIA] ([MaLoaiDocGia], [TenLoaiDocGia], [SoSachToiDa], [ThoiHanMuon]) VALUES (N'LDG2', N'Giảng Viên', 3, 10)
INSERT [dbo].[LOAIDOCGIA] ([MaLoaiDocGia], [TenLoaiDocGia], [SoSachToiDa], [ThoiHanMuon]) VALUES (N'LDG3', N'Nhân Viên', 2, 5)
--insert độc giả
INSERT [dbo].[DOCGIA] ([MaDocGia], [HoTen], [NgaySinh], [DiaChi], [Email], [NgayLapThe], [NgayHetHan], [MaLoaiDocGia], [IDAccount], [SDT]) VALUES (N'DG000001', N'Nguyễn Thị Ngọc Ánh', CAST(0xA7220B00 AS Date), N'Hà Nội', N'11235546@st.neu.edu.vn', CAST(0x5F3F0B00 AS Date), CAST(0xF83F0B00 AS Date), N'LDG1', N'100000', N'01639893353')
INSERT [dbo].[DOCGIA] ([MaDocGia], [HoTen], [NgaySinh], [DiaChi], [Email], [NgayLapThe], [NgayHetHan], [MaLoaiDocGia], [IDAccount], [SDT]) VALUES (N'DG000002', N'Đặng Quang Minh', CAST(0xA7220B00 AS Date), N'Bình Dương', N'11245546@st.neu.edu.vn', CAST(0xA33F0B00 AS Date), CAST(0x3C400B00 AS Date), N'LDG1', N'100001', N'0868992467')
INSERT [dbo].[DOCGIA] ([MaDocGia], [HoTen], [NgaySinh], [DiaChi], [Email], [NgayLapThe], [NgayHetHan], [MaLoaiDocGia], [IDAccount], [SDT]) VALUES (N'DG000003', N'Vũ Thị Hồng Lam', CAST(0xB0230B00 AS Date), N'Lâm Đồng', N'11255546@st.neu.edu.vn', CAST(0xA73F0B00 AS Date), CAST(0x40400B00 AS Date), N'LDG2', N'100002', N'0583335622')
INSERT [dbo].[DOCGIA] ([MaDocGia], [HoTen], [NgaySinh], [DiaChi], [Email], [NgayLapThe], [NgayHetHan], [MaLoaiDocGia], [IDAccount], [SDT]) VALUES (N'DG000004', N'Dương Thành Đạt', CAST(0xE2220B00 AS Date), N'TpHCM', N'11235547@st.neu.edu.vn', CAST(0x4E3F0B00 AS Date), CAST(0xE43F0B00 AS Date), N'LDG3', N'100003', N'0903533820')
--insert thể loại
INSERT into  THELOAI values 
('TL1',N'Giáo trình'),
('TL2',N'Tạp chí'),
('TL3',N'Sách tham khảo'),
('TL4',N'Tài liệu khác');

Alter table DAUSACH
ADD SoLuong int not null default 0; 

UPDATE DAUSACH set SoLuong = 3 where MaDauSach = 1; 
UPDATE DAUSACH set SoLuong = 3 where MaDauSach = 2; 
UPDATE DAUSACH set SoLuong = 1 where MaDauSach = 3; 
UPDATE DAUSACH set SoLuong = 1 where MaDauSach = 4; 
UPDATE DAUSACH set SoLuong = 2 where MaDauSach = 5; 




